// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalonSamochodowy.Entities;

#nullable disable

namespace SalonSamochodowy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SalonSamochodowy.Entities.AppRole", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleID");

                    b.ToTable("AppRoles");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.AppUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NIP")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClientID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Dealership", b =>
                {
                    b.Property<int>("DealershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("DealershipID");

                    b.ToTable("Dealerships");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Engine", b =>
                {
                    b.Property<int>("EngineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineSize")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("EngineID");

                    b.ToTable("Engines");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Feature", b =>
                {
                    b.Property<int>("FeatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("FeatureID");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Job", b =>
                {
                    b.Property<int>("JobID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobID");

                    b.HasIndex("FeatureID");

                    b.HasIndex("VehicleID");

                    b.HasIndex("WorkerID");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.SalesOrder", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealershipID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderID");

                    b.HasIndex("ClientID");

                    b.HasIndex("DealershipID");

                    b.HasIndex("VehicleID");

                    b.HasIndex("WorkerID");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.TrimFeature", b =>
                {
                    b.Property<int>("TrimID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStandard")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrimID", "FeatureID");

                    b.HasIndex("FeatureID");

                    b.ToTable("TrimFeatures");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.TrimLevel", b =>
                {
                    b.Property<int>("TrimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrimName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("TrimID");

                    b.HasIndex("ModelID");

                    b.ToTable("TrimLevels");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealershipID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EngineID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mileage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrimID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleID");

                    b.HasIndex("DealershipID");

                    b.HasIndex("EngineID");

                    b.HasIndex("TrimID");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.VehicleFeature", b =>
                {
                    b.Property<int>("VehicleID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleID", "FeatureID");

                    b.HasIndex("FeatureID");

                    b.ToTable("VehicleFeatures");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.VehicleModel", b =>
                {
                    b.Property<int>("ModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ModelID");

                    b.ToTable("VehicleModels");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Worker", b =>
                {
                    b.Property<int>("WorkerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealershipID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndOfContractDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Payroll")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkerID");

                    b.HasIndex("DealershipID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.AppUser", b =>
                {
                    b.HasOne("SalonSamochodowy.Entities.AppRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Client", b =>
                {
                    b.HasOne("SalonSamochodowy.Entities.AppUser", "User")
                        .WithOne("Client")
                        .HasForeignKey("SalonSamochodowy.Entities.Client", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Job", b =>
                {
                    b.HasOne("SalonSamochodowy.Entities.Feature", "Feature")
                        .WithMany("Jobs")
                        .HasForeignKey("FeatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonSamochodowy.Entities.Vehicle", "Vehicle")
                        .WithMany("Jobs")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonSamochodowy.Entities.Worker", "Worker")
                        .WithMany("Jobs")
                        .HasForeignKey("WorkerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Vehicle");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.SalesOrder", b =>
                {
                    b.HasOne("SalonSamochodowy.Entities.Client", "Client")
                        .WithMany("SalesOrders")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonSamochodowy.Entities.Dealership", "Dealership")
                        .WithMany("SalesOrders")
                        .HasForeignKey("DealershipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonSamochodowy.Entities.Vehicle", "Vehicle")
                        .WithMany("SalesOrders")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonSamochodowy.Entities.Worker", "Worker")
                        .WithMany("SalesOrders")
                        .HasForeignKey("WorkerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Dealership");

                    b.Navigation("Vehicle");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.TrimFeature", b =>
                {
                    b.HasOne("SalonSamochodowy.Entities.Feature", "Feature")
                        .WithMany("TrimFeatures")
                        .HasForeignKey("FeatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonSamochodowy.Entities.TrimLevel", "Trim")
                        .WithMany("TrimFeatures")
                        .HasForeignKey("TrimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Trim");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.TrimLevel", b =>
                {
                    b.HasOne("SalonSamochodowy.Entities.VehicleModel", "Model")
                        .WithMany("TrimLevels")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Vehicle", b =>
                {
                    b.HasOne("SalonSamochodowy.Entities.Dealership", "Dealership")
                        .WithMany("Vehicles")
                        .HasForeignKey("DealershipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonSamochodowy.Entities.Engine", "Engine")
                        .WithMany("Vehicles")
                        .HasForeignKey("EngineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonSamochodowy.Entities.TrimLevel", "Trim")
                        .WithMany("Vehicles")
                        .HasForeignKey("TrimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");

                    b.Navigation("Engine");

                    b.Navigation("Trim");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.VehicleFeature", b =>
                {
                    b.HasOne("SalonSamochodowy.Entities.Feature", "Feature")
                        .WithMany("VehicleFeatures")
                        .HasForeignKey("FeatureID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonSamochodowy.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleFeatures")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Worker", b =>
                {
                    b.HasOne("SalonSamochodowy.Entities.Dealership", "Dealership")
                        .WithMany("Workers")
                        .HasForeignKey("DealershipID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SalonSamochodowy.Entities.AppUser", "User")
                        .WithOne("Worker")
                        .HasForeignKey("SalonSamochodowy.Entities.Worker", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.AppRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.AppUser", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Client", b =>
                {
                    b.Navigation("SalesOrders");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Dealership", b =>
                {
                    b.Navigation("SalesOrders");

                    b.Navigation("Vehicles");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Engine", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Feature", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("TrimFeatures");

                    b.Navigation("VehicleFeatures");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.TrimLevel", b =>
                {
                    b.Navigation("TrimFeatures");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Vehicle", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("SalesOrders");

                    b.Navigation("VehicleFeatures");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.VehicleModel", b =>
                {
                    b.Navigation("TrimLevels");
                });

            modelBuilder.Entity("SalonSamochodowy.Entities.Worker", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("SalesOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
